apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcache
  namespace: slate-group-atlas-xcache 
  labels:
    app: xcache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcache
    
  template:
    metadata:
      labels:
        app: xcache
    spec:

      nodeSelector:
        xcache-capable: "true"
      
      tolerations:
      - key: "special"
        operator: "Exists"
        effect: PreferNoSchedule

      volumes:
      - name: x509-data
        emptyDir: {}
      - name: x509-certs-volume
        secret:
          secretName: xcache-cert-secret
          items:
          - key: userkey
            path: userkey.pem
            mode: 256 
          - key: usercert
            path: usercert.pem
      - name: xcache-data-0
        hostPath:
          path: /scratch/1
      - name: xcache-data-1
        hostPath:
          path: /scratch/2
      - name: xcache-data-2
        hostPath:
          path: /scratch/3
      - name: xcache-data-3
        hostPath:
          path: /scratch/4
      - name: xcache-data-4
        hostPath:
          path: /scratch/5
      - name: xcache-data-5
        hostPath:
          path: /scratch/6
      - name: xcache-data-6
        hostPath:
          path: /scratch/7
      - name: xcache-data-7
        hostPath:
          path: /scratch/8
      - name: xcache-data-8
        hostPath:
          path: /scratch/9
      - name: xcache-data-9
        hostPath:
          path: /scratch/10
      - name: xcache-data-10
        hostPath:
          path: /scratch/11
      - name: xcache-data-11
        hostPath:
          path: /scratch/12
      - name: xcache-data-12
        hostPath:
          path: /scratch/13
      - name: xcache-data-13
        hostPath:
          path: /scratch/14
      - name: xcache-data-14
        hostPath:
          path: /scratch/15
      - name: xcache-data-15
        hostPath:
          path: /scratch/16
      - name: xcache-meta
        hostPath:
          path: /scratch/meta
      
      hostNetwork: true

      containers:
        - name: xcache
          image: "slateci/xcache:experimental"
          imagePullPolicy: Always
          env:
          - name: XC_SPACE_HIGH_WM
            value: "0.95"
          - name: XC_SPACE_LOW_WM
            value: "0.90"
          - name: XC_PORT
            value: "1094"
          - name: XC_RAMSIZE
            value: "16g"
          - name: XC_BLOCKSIZE
            value: "1M"
          - name: XC_PREFETCH
            value: "0"
          - name: AGIS_PROTOCOL_ID
            value: "399"
          - name: WQ_BLOCKS_PER_LOOP
            value: "10"
          - name: WQ_THREADS
            value: "2"
          resources:
            requests:
              ephemeral-storage: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 1094
            initialDelaySeconds: 180
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                command: ["./updateAGISstatus.sh","399","DISABLED"]
          ports:
            - containerPort: 1094         
          volumeMounts:
          - name: x509-data
            mountPath: "/etc/grid-security/"
            readOnly: false
          - name: x509-certs-volume
            mountPath: "/etc/grid-certs/"
            readOnly: true
          - name: xcache-data-0
            mountPath: "/xcache-data_0"
          - name: xcache-data-1
            mountPath: "/xcache-data_1"
          - name: xcache-data-2
            mountPath: "/xcache-data_2"
          - name: xcache-data-3
            mountPath: "/xcache-data_3"
          - name: xcache-data-4
            mountPath: "/xcache-data_4"
          - name: xcache-data-5
            mountPath: "/xcache-data_5"
          - name: xcache-data-6
            mountPath: "/xcache-data_6"
          - name: xcache-data-7
            mountPath: "/xcache-data_7"
          - name: xcache-data-8
            mountPath: "/xcache-data_8"
          - name: xcache-data-9
            mountPath: "/xcache-data_9"
          - name: xcache-data-10
            mountPath: "/xcache-data_10"
          - name: xcache-data-11
            mountPath: "/xcache-data_11"
          - name: xcache-data-12
            mountPath: "/xcache-data_12"
          - name: xcache-data-13
            mountPath: "/xcache-data_13"
          - name: xcache-data-14
            mountPath: "/xcache-data_14"
          - name: xcache-data-15
            mountPath: "/xcache-data_15"
          - name: xcache-meta
            mountPath: "/xcache-meta"

        - name: x509
          image: "slateci/xcache:experimental"
          command: ["/run_x509_updater.sh"]
          resources:
            requests:
              ephemeral-storage: "1Gi"
          volumeMounts:
          - name: x509-data
            mountPath: "/etc/grid-security/"
            readOnly: false
          - name: x509-certs-volume
            mountPath: "/etc/grid-certs/"
            readOnly: true

        - name: reporter
          image: "slateci/xcache:experimental"
          command: ["/run_cache_reporter.sh"]
          env:
          - name: XC_SITE
            value: "MWT2"
          - name: XC_REPORT_COLLECTOR
            value: "http://uct2-collectd.mwt2.org:8080"
          volumeMounts:
          - name: xcache-meta
            mountPath: "/xcache-meta"
            readOnly: true