kind: Service
apiVersion: v1
metadata:
  name: xcache-service
spec:
  type: NodePort
  selector:
    app: xcache
  ports:
    - protocol: TCP
      name: xrootd
      port: 1094
      targetPort: 1094
      nodePort: 31094
---
kind: Pod
apiVersion: v1
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:
  volumes:
    - name: x509-data
      emptyDir: {}
    - name: x509-certs-volume
      secret:
        secretName: xcache-cert-secret
        items:
          - key: userkey
            path: userkey.pem
            mode: 256
          - key: usercert
            path: usercert.pem
    - name: xcache-data
      hostPath:
        path: /tmp
    - name: xcache-meta
      hostPath:
        path: /tmp

  containers:
    - name: xcache
      image: ivukotic/xcache:standalone
      # image: xcache:standalone
      command: ["sleep"]
      args: ["36500000"]
      imagePullPolicy: Always
      # imagePullPolicy: Never
      env:
        - name: DISABLE_OSG_MONITORING
          value: "true"
        - name: XC_PORT
          value: "1094"
      volumeMounts:
        - name: x509-data
          mountPath: "/etc/grid-security/"
          readOnly: false
        - name: x509-certs-volume
          mountPath: "/etc/grid-certs/"
          readOnly: true
        - name: xcache-data
          mountPath: "/xcache/data"
        - name: xcache-meta
          mountPath: "/xcache/meta"
      ports:
        - containerPort: 1094

    - name: x509
      image: ivukotic/xcache:standalone
      # image: xcache:standalone
      imagePullPolicy: Always
      # imagePullPolicy: Never
      # command: ["/usr/local/sbin/run_x509_updater.sh"]
      command: ["sleep"]
      args: ["36500000"]
      volumeMounts:
        - name: x509-data
          mountPath: "/etc/grid-security/"
          readOnly: false
        - name: x509-certs-volume
          mountPath: "/etc/grid-certs/"
          readOnly: true

  restartPolicy: Never
