kind: Service
apiVersion: v1
metadata:
  name: xcache-service
spec:
  type: NodePort
  selector:
    app: xcache
  ports:
  - protocol: TCP
    name: xrootd
    port: 1094
    targetPort: 1094
    nodePort: 31094
  externalIPs:
  - 192.170.227.151
---
kind: Pod
apiVersion: v1
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:

  nodeSelector:
    xcache-capable: "true"

  volumes:
  - name: x509-data
    emptyDir: {}
  - name: x509-certs-volume
    secret:
      secretName: xcache-cert-secret
      items:
      - key: userkey
        path: userkey.pem
        mode: 256 
      - key: usercert
        path: usercert.pem
  - name: xcache-data-1
    hostPath:
      path: /tmp
  - name: xcache-meta
    hostPath:
      path: /scratch

  containers:
  - name: xcache
    image: slateci/xcache:testing
    env:
    - name: XC_SPACE_HIGH_WM
      value: "0.95"
    - name: XC_SPACE_LOW_WM
      value: "0.90"
    - name: XC_PORT
      value: "1094"
    - name: XC_RAMSIZE
      value: "16g"
    - name: XC_BLOCKSIZE
      value: "1M"
    - name: XC_PREFETCH
      value: "0"
    - name: AGIS_PROTOCOL_ID
      value: "433"
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: false
    - name: x509-certs-volume
      mountPath: "/etc/grid-certs/"
      readOnly: true
    - name: xcache-data-1
      mountPath: "/xcache-data_1"
    - name: xcache-meta
      mountPath: "/xcache-meta"
    ports:
      - containerPort: 1094

  - name: x509
    image: slateci/xcache:testing
    command: ["/run_x509_updater.sh"]
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: false
    - name: x509-certs-volume
      mountPath: "/etc/grid-certs/"
      readOnly: true
      
  restartPolicy: Never