# Instance to label use case of XCache deployment
# Generates app name as "xcache-[Instance]"
# Enables unique instances of XCache in one namespace
Instance: global

Service:
  # Port that the service will utilize.
  Port: 1094
  # External IP that may access the service
  # 192.170.227.151 - localhost
  # 192.170.227.231 - ml node - root://xcache.mwt2.org:1094
  ExternalIP: 192.170.227.151 

SiteConfig:
  Name: MWT2
  # AGIS protocol ID. 433 is a dummy value. 
  # can be looked up in this URL: http://atlas-agis.cern.ch/agis/serviceprotocol/edit/433/
  AGISprotocolID: 433
  CRICprotocolID: 433

Monitoring:
  Collector: http://uct2-collectd.mwt2.org:8080
  GStreamCollector: 192.170.227.234:9000 

XCacheConfig:
  # Local directories to be used as a cache
  CacheDirectories:
    - path: /scratch_HOT
    - path: /scratch_B
  MetaDirectory: /scratch_meta
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90
  
  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 16g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 1M
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # Write queue parameters
  WQBlocksPerLoop: 10
  WQThreads: 2
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret


image:
  repository: slateci/xcache
  tag: latest
  pullPolicy: Always
